name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: hid 1
      id: hid-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: hid 1
        setup-command: gcc main.c -o main
        command: "./main"
        input: 10 20
        expected-output: '30'
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: hid 2
      id: hid-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: hid 2
        setup-command: gcc main.c -o main
        command: "./main"
        input: 50 30
        expected-output: '80'
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HID-1_RESULTS: "${{steps.hid-1.outputs.result}}"
        HID-2_RESULTS: "${{steps.hid-2.outputs.result}}"
      with:
        runners: hid-1,hid-2
